export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

export const USER_LOADING = "USER_LOADING";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";
export const GET_SINGLE_USER = "GET_SINGLE_USER"
export const GET_SINGLE_USER_ERROR = "GET_SINGLE_USER_ERROR"
export const GET_USERS = "GET_USERS";
export const GET_USERS_ERROR = "GET_USERS_ERROR"
export const UPDATED_USER_SUCCESS = "UPDATED_USER_SUCCESS"
export const UPDATED_USER_ERROR = "UPDATED_USER_ERROR"
export const UPDATED_USER_LOADING = "UPDATED_USER_LOADING"

export const POST_LOADING = "POST_LOADING";
export const POSTS_SUCCESS = "POSTS_SUCCESS";
export const POST_ERROR = "POST_ERROR";
export const MY_POSTS = "MY_POSTS";
export const UPLOAD_POST = "UPLOAD_POST";
export const SINGLE_POST = "SINGLE_POST"
export const DELETE_POST = "DELETE_POST"

export const COMMENT_LOADING = "COMMENT_LOADING";
export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_ERROR = "COMMENT_ERROR";
export const GET_ALL_COMMENTS = "GET_ALL_COMMENTS";
export const ERROR_ALL_COMMENTS = "ERROR_ALL_COMMENTS";
export const COMMENTS_BY_ID = "COMMENTS_BY_ID"

export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";

export const GET_LIKES = "GET_LIKES";
export const LIKE_POST = "LIKE_POST";
export const UNLIKE_POST = "UNLIKE_POST";
export const LIKE_POST_ERROR = "LIKE_POST_ERROR";

export const LIKE_COMMENT = "LIKE_COMMENT";
export const LIKE_COMMENT_ERROR = "LIKE_COMMENT_ERROR"

export const GET_ROOMS = "GET_ROOMS"
export const ERROR_ROOMS = "ERROR_ROOMS"
export const GET_ROOM = "GET_ROOM"

export const GET_PLACES = "GET_PLACES";
export const GET_PLACES_LOADING = "GET_PLACES_LOADING"
export const GET_PLACES_ERROR = "GET_PLACES_ERROR"
export const GET_PLACE_PHOTO = "GET_PLACE_PHOTO"
export const GET_PLACE_DETAILS = "GET_PLACE_DETAILS"